
import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./fonts";
import StoreProviders from "./components/StoreProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProviders >
          {children}
        </StoreProviders>
      </body>
    </html>
  );
}
